const data = {
    "bugs" : [ { '#': '1',
    Name: 'Common Butterfly',
    Image: '',
    Price: '90',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: 'March - June: 4 AM - 7 PMSeptember: 8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '2',
    Name: 'Yellow Butterfly',
    Image: '',
    Price: '90',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: 'March - June: 4 AM - 7 PMSeptember: 8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '3',
    Name: 'Tiger Butterfly',
    Image: '',
    Price: '160',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers(red and pink)',
    Time: 'March - June: 4 AM - 7 PMJuly - August: 8 AM - 5 PMSeptember: 8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '4',
    Name: 'Peacock Butterfly',
    Image: '',
    Price: '220',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers(blue, violet and black)',
    Time: 'March - June: 4 AM - 7 PMJuly: 4 AM - 5 PMAugust: 8 AM - 5 PMSeptember: 8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '5',
    Name: 'Monarch Butterfly',
    Image: '',
    Price: '90',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: 'September - October: 4 AM - 5 PMNovember: 8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '6',
    Name: 'Emperor Butterfly',
    Image: '',
    Price: '2,500',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '7',
    Name: 'Agrias Butterfly',
    Image: '',
    Price: '3,000',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '8',
    Name: 'Raja Brooke Butterfly',
    Image: '',
    Price: '2,500',
    Rarity: '-',
    Average: '-',
    Location: 'Near freshwater',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '9',
    Name: 'Birdwing Butterfly',
    Image: '',
    Price: '4,000',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: '8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '10',
    Name: 'Moth',
    Image: '',
    Price: '60',
    Rarity: '-',
    Average: '-',
    Location: 'Near outdoor lights',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '11',
    Name: 'Oak Silk Moth',
    Image: '',
    Price: '1,200',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '12',
    Name: 'Honeybee',
    Image: '',
    Price: '100',
    Rarity: '-',
    Average: '-',
    Location: 'Near flowers',
    Time: 'March - June: 8 AM - 5 PMJuly: 8 AM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '13',
    Name: 'Bee',
    Image: '',
    Price: '4,500',
    Rarity: '-',
    Average: '-',
    Location: 'In trees',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '14',
    Name: 'Long Locust',
    Image: '',
    Price: '200',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: '8 AM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '15',
    Name: 'Migratory Locust',
    Image: '',
    Price: '600',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: '8 AM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '16',
    Name: 'Rice Grasshopper',
    Image: '',
    Price: '400',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '17',
    Name: 'Mantis',
    Image: '',
    Price: '430',
    Rarity: '-',
    Average: '-',
    Location: 'On flowers',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '18',
    Name: 'Orchid Mantis',
    Image: '',
    Price: '2,400',
    Rarity: '-',
    Average: '-',
    Location: 'On white flowers',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '19',
    Name: 'Brown Cicada',
    Image: '',
    Price: '200',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '20',
    Name: 'Robust Cicada',
    Image: '',
    Price: '300',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '21',
    Name: 'Giant Cicada',
    Image: '',
    Price: '500',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '22',
    Name: 'Walker Cicada',
    Image: '',
    Price: '400',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '23',
    Name: 'Evening Cicada',
    Image: '',
    Price: '550',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '4 AM - 8 AM4 PM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '24',
    Name: 'Cicada Shell',
    Image: '',
    Price: '100',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '25',
    Name: 'Lantern Fly',
    Image: '',
    Price: '1,800',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'June: 4 PM - 7 PMJuly - August: 4 PM - 8 AMSeptember: 11 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '26',
    Name: 'Red Dragonfly',
    Image: '',
    Price: '80',
    Rarity: '-',
    Average: '-',
    Location: 'In air',
    Time: '8 AM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '27',
    Name: 'Darner Dragonfly',
    Image: '',
    Price: '200',
    Rarity: '-',
    Average: '-',
    Location: 'In air',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '28',
    Name: 'Banded Dragonfly',
    Image: '',
    Price: '4,500',
    Rarity: '-',
    Average: '-',
    Location: 'In air',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '29',
    Name: 'Petaltail Dragonfly',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'In air',
    Time: '5 PM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '30',
    Name: 'Ant',
    Image: '',
    Price: '80',
    Rarity: '-',
    Average: '-',
    Location: 'On candy or spoiled turnips',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '31',
    Name: 'Pondskater',
    Image: '',
    Price: '130',
    Rarity: '-',
    Average: '-',
    Location: 'On freshwater',
    Time: '8 AM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '32',
    Name: 'Diving Beetle',
    Image: '',
    Price: '800',
    Rarity: '-',
    Average: '-',
    Location: 'In/On freshwater',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '33',
    Name: 'Stinkbug',
    Image: '',
    Price: '120',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '34',
    Name: 'Snail',
    Image: '',
    Price: '250',
    Rarity: '-',
    Average: '-',
    Location: 'On flowers',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '35',
    Name: 'Cricket',
    Image: '',
    Price: '130',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '36',
    Name: 'Bell Cricket',
    Image: '',
    Price: '430',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '37',
    Name: 'Grasshopper',
    Image: '',
    Price: '160',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: 'July: 4 PM - 5 PMAugust - September: 8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '38',
    Name: 'Mole Cricket',
    Image: '',
    Price: '280',
    Rarity: '-',
    Average: '-',
    Location: 'Underground',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '39',
    Name: 'Walking Leaf',
    Image: '',
    Price: '600',
    Rarity: '-',
    Average: '-',
    Location: 'On ground',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '40',
    Name: 'Walkingstick',
    Image: '',
    Price: '600',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'July - August: 4 AM - 8 AM / 5 PM - 7 PMSeptember - November: 4 AM - 7 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '41',
    Name: 'Bagworm',
    Image: '',
    Price: '300',
    Rarity: '-',
    Average: '-',
    Location: 'In trees',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '42',
    Name: 'Ladybug',
    Image: '',
    Price: '200',
    Rarity: '-',
    Average: '-',
    Location: 'On flowers',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '43',
    Name: 'Violin Beetle',
    Image: '',
    Price: '250',
    Rarity: '-',
    Average: '-',
    Location: 'On tree stumps',
    Time: 'June: 4 AM - 7 PM September - October: 4 AM - 5 PM November: 8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '44',
    Name: 'Longhorn Beetle',
    Image: '',
    Price: '260',
    Rarity: '-',
    Average: '-',
    Location: 'On tree stumps',
    Time: '11 PM - 6 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '45',
    Name: 'Tiger Beetle',
    Image: '',
    Price: '1500',
    Rarity: '-',
    Average: '-',
    Location: 'In grass',
    Time: 'March - September: 8 AM - 7 PMOctober: 4 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '46',
    Name: 'Dung Beetle',
    Image: '',
    Price: '800',
    Rarity: '-',
    Average: '-',
    Location: 'Rolling snowballs',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '47',
    Name: 'Wharf Roach',
    Image: '',
    Price: '200',
    Rarity: '-',
    Average: '-',
    Location: 'On beach',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '48',
    Name: 'Hermit Crab',
    Image: '',
    Price: '1000',
    Rarity: '-',
    Average: '-',
    Location: 'On beach',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '49',
    Name: 'Firefly',
    Image: '',
    Price: '300',
    Rarity: '-',
    Average: '-',
    Location: 'Near freshwater',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '50',
    Name: 'Fruit Beetle',
    Image: '',
    Price: '100',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'July - August: All daySeptember: 7 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '51',
    Name: 'Scarab Beetle',
    Image: '',
    Price: '6,000',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '11 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '52',
    Name: 'Jewel Beetle',
    Image: '',
    Price: '2,400',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '8 AM - 5 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '53',
    Name: 'Miyama Stag',
    Image: '',
    Price: '1,000',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '54',
    Name: 'Saw Stag Beetle',
    Image: '',
    Price: '2,000',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '55',
    Name: 'Giant Beetle',
    Image: '',
    Price: '10,000',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '11 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '56',
    Name: 'Rainbow Stag',
    Image: '',
    Price: '10,000',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '57',
    Name: 'Cyclommatus',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '58',
    Name: 'Golden Stag',
    Image: '',
    Price: '12,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: '5 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '59',
    Name: 'Horned Dynastid',
    Image: '',
    Price: '1,350',
    Rarity: '-',
    Average: '-',
    Location: 'On trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '60',
    Name: 'Horned Atlas',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '61',
    Name: 'Horned Elephant',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '62',
    Name: 'Horned Hercules',
    Image: '',
    Price: '12,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: '5 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '63',
    Name: 'Goliath Beetle',
    Image: '',
    Price: '6,000',
    Rarity: '-',
    Average: '-',
    Location: 'On palm trees',
    Time: 'June: 7 PM - 8 AMJuly - August: 5 PM - 8 AMSeptember: 7 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '64',
    Name: 'Flea',
    Image: '',
    Price: '70',
    Rarity: '-',
    Average: '-',
    Location: 'On villagers',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '65',
    Name: 'Pill Bug',
    Image: '',
    Price: '250',
    Rarity: '-',
    Average: '-',
    Location: 'Under rocks',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '66',
    Name: 'Mosquito',
    Image: '',
    Price: '130',
    Rarity: '-',
    Average: '-',
    Location: 'In air',
    Time: '5 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '67',
    Name: 'Fly',
    Image: '',
    Price: '60',
    Rarity: '-',
    Average: '-',
    Location: 'Near spoiled turnips',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '68',
    Name: 'House Centipede',
    Image: '',
    Price: '1000',
    Rarity: '-',
    Average: '-',
    Location: 'Under rocks',
    Time: '7 PM - 8 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '69',
    Name: 'Centipede',
    Image: '',
    Price: '300',
    Rarity: '-',
    Average: '-',
    Location: 'Under rocks',
    Time: '4 PM - 11 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '70',
    Name: 'Spider',
    Image: '',
    Price: '300',
    Rarity: '-',
    Average: '-',
    Location: 'In trees',
    Time: 'March - June: All dayJuly - August: 7 PM - 8 AMSeptember: All dayOctober: 11 PM - 4 PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '71',
    Name: 'Tarantula',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'On ground',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' },
  { '#': '72',
    Name: 'Scorpion',
    Image: '',
    Price: '8,000',
    Rarity: '-',
    Average: '-',
    Location: 'On ground',
    Time: '7 PM - 4 AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '-' } ],

    "fish" : [ { '#': '1',
    Name: 'Bitterling',
    Image: '',
    Price: '900',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '2',
    Name: 'Pale Chub',
    Image: '',
    Price: '160',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '3',
    Name: 'Crucian Carp',
    Image: '',
    Price: '120',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '4',
    Name: 'Dace',
    Image: '',
    Price: '200',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '5',
    Name: 'Barbel Steed',
    Image: '',
    Price: '200',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '6',
    Name: 'Carp',
    Image: '',
    Price: '300',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '7',
    Name: 'Koi',
    Image: '',
    Price: '4,000',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '8',
    Name: 'Goldfish',
    Image: '',
    Price: '1,300',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '9',
    Name: 'Popeyed Goldfish',
    Image: '',
    Price: '1,300',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '10',
    Name: 'Killifish',
    Image: '',
    Price: '240',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'Holding pond',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '11',
    Name: 'Crawfish',
    Image: '',
    Price: '200',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'Holding pond',
    Time: 'All day',
    Months: 'J F M A M J J A S* O N D',
    Peak: '???' },
  { '#': '12',
    Name: 'Soft-Shelled Turtle',
    Image: '',
    Price: '3,750',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '13',
    Name: 'Tadpole',
    Image: '',
    Price: '100',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'Holding pond',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '14',
    Name: 'Frog',
    Image: '',
    Price: '120',
    Shadow: 'Small1',
    Average: '???',
    Tank: '???',
    Location: 'Holding pond',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '15',
    Name: 'Freshwater Goby',
    Image: '',
    Price: '300',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '16',
    Name: 'Loach',
    Image: '',
    Price: '300',
    Shadow: 'Small-medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '17',
    Name: 'Catfish',
    Image: '',
    Price: '800',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River pool',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '18',
    Name: 'Eel',
    Image: '',
    Price: '2,000',
    Shadow: 'Long & thin',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '19',
    Name: 'Giant Snakehead',
    Image: '',
    Price: '5,500',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '20',
    Name: 'Bluegill',
    Image: '',
    Price: '120',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4AM - 9PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '21',
    Name: 'Yellow Perch',
    Image: '',
    Price: '240',
    Shadow: 'Small-medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '22',
    Name: 'Black Bass',
    Image: '',
    Price: '300',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '23',
    Name: 'Pike',
    Image: '',
    Price: '1,800',
    Shadow: 'Medium-large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4AM - 9PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '24',
    Name: 'Pond Smelt',
    Image: '',
    Price: '300',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '25',
    Name: 'Sweetfish',
    Image: '',
    Price: '900',
    Shadow: 'Small-medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S* O N D',
    Peak: '???' },
  { '#': '26',
    Name: 'Cherry Salmon',
    Image: '',
    Price: '1,000',
    Shadow: 'Small-medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'March-June: 4AM - 9AM & 4PM - 9PMSeptember - November: 9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '27',
    Name: 'Char',
    Image: '',
    Price: '3,800',
    Shadow: 'Small-medium',
    Average: '???',
    Tank: '???',
    Location: 'Waterfall',
    Time: 'March-June: 4AM - 9AM & 4PM - 9PMSeptember - November: 9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '28',
    Name: 'Rainbow Trout',
    Image: '',
    Price: '800',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: 'March-June: 4AM - 9AM & 4PM - 9PMSeptember - November: 9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '29',
    Name: 'Stringfish',
    Image: '',
    Price: '15,000',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '30',
    Name: 'Salmon',
    Image: '',
    Price: '700',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'River and ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '31',
    Name: 'King Salmon',
    Image: '',
    Price: '1,800',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'River mouth',
    Time: 'All day',
    Months: 'J F M A M J J A* S O N D',
    Peak: '???' },
  { '#': '32',
    Name: 'Mitten Crab',
    Image: '',
    Price: '2,000',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S* O N D',
    Peak: '???' },
  { '#': '33',
    Name: 'Guppy',
    Image: '',
    Price: '1,300',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '34',
    Name: 'Nibble Fish',
    Image: '',
    Price: '1,200',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '35',
    Name: 'Angelfish',
    Image: '',
    Price: '3,000',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '36',
    Name: 'Neon Tetra',
    Image: '',
    Price: '500',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '37',
    Name: 'Piranha',
    Image: '',
    Price: '2,500',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9AM - 4PM & 9PM - 4AM',
    Months: 'J F M A M J J A S* O N D',
    Peak: '???' },
  { '#': '38',
    Name: 'Arowana',
    Image: '',
    Price: '10,000',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '39',
    Name: 'Dorado',
    Image: '',
    Price: '15,000',
    Shadow: 'Very large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4AM - 9PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '40',
    Name: 'Gar',
    Image: '',
    Price: '6,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'River pool',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '41',
    Name: 'Arapaima',
    Image: '',
    Price: '10,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '42',
    Name: 'Saddled Bichir',
    Image: '',
    Price: '4,000',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'River',
    Time: '9PM - 4AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '43',
    Name: 'Sea Butterfly',
    Image: '',
    Price: '1,000',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '44',
    Name: 'Seahorse',
    Image: '',
    Price: '1,100',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '45',
    Name: 'Clownfish',
    Image: '',
    Price: '650',
    Shadow: 'Tiny',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '46',
    Name: 'Surgeonfish',
    Image: '',
    Price: '1,000',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '47',
    Name: 'Butterfly Fish',
    Image: '',
    Price: '1,000',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '48',
    Name: 'Napoleonfish',
    Image: '',
    Price: '10,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '49',
    Name: 'Zebra Turkeyfish',
    Image: '',
    Price: '400',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '50',
    Name: 'Blowfish',
    Image: '',
    Price: '5,000',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '9PM - 4AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '51',
    Name: 'Puffer Fish',
    Image: '',
    Price: '240',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '52',
    Name: 'Horse Mackerel',
    Image: '',
    Price: '150',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '53',
    Name: 'Barred Knifejaw',
    Image: '',
    Price: '5,000',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '54',
    Name: 'Sea Bass',
    Image: '',
    Price: '200',
    Shadow: 'Very large',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '55',
    Name: 'Red Snapper',
    Image: '',
    Price: '3,000',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '56',
    Name: 'Dab',
    Image: '',
    Price: '300',
    Shadow: 'Medium',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '57',
    Name: 'Olive Flounder',
    Image: '',
    Price: '800',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '58',
    Name: 'Squid',
    Image: '',
    Price: '400',
    Shadow: 'Small',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A* S O N D',
    Peak: '???' },
  { '#': '59',
    Name: 'Moray Eel',
    Image: '',
    Price: '2,000',
    Shadow: 'Very large',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '60',
    Name: 'Ribbon Eel',
    Image: '',
    Price: '600',
    Shadow: 'Thin',
    Average: '???',
    Tank: '???',
    Location: 'Tortimer Island',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '61',
    Name: 'Football Fish',
    Image: '',
    Price: '2,500',
    Shadow: 'Large',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '62',
    Name: 'Tuna',
    Image: '',
    Price: '7,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '63',
    Name: 'Blue Marlin',
    Image: '',
    Price: '10,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '64',
    Name: 'Giant Trevally',
    Image: '',
    Price: '4,500',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Tortimer Island',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '65',
    Name: 'Ray',
    Image: '',
    Price: '3,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '4AM - 9PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '66',
    Name: 'Ocean Sunfish',
    Image: '',
    Price: '4,000',
    Shadow: 'Huge (with fin)',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '4AM - 9PM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '67',
    Name: 'Hammerhead Shark',
    Image: '',
    Price: '8,000',
    Shadow: 'Huge (with fin)',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '68',
    Name: 'Shark',
    Image: '',
    Price: '15,000',
    Shadow: 'Huge (with fin)',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '69',
    Name: 'Saw Shark',
    Image: '',
    Price: '12,000',
    Shadow: 'Huge (with fin)',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '70',
    Name: 'Whale Shark',
    Image: '',
    Price: '13,000',
    Shadow: 'Huge (with fin)',
    Average: '???',
    Tank: '???',
    Location: 'Tortimer Island',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '71',
    Name: 'Oarfish',
    Image: '',
    Price: '9,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean',
    Time: 'All day',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' },
  { '#': '72',
    Name: 'Coelacanth',
    Image: '',
    Price: '15,000',
    Shadow: 'Huge',
    Average: '???',
    Tank: '???',
    Location: 'Ocean1',
    Time: '4PM - 9AM',
    Months: 'J F M A M J J A S O N D',
    Peak: '???' } ],
    "arts" : [ { Name: 'Amazing Painting',
      src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/714px-Rembrandt_nightwatch_large.jpg',
    Description: 'If the man in white is on the left and the man in black is on the right, it is fake. If the man in white is on the right and the man in black is on the left, it is genuine.' },
  { Name: 'Basic Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/300px-Thomas_Gainsborough_008.jpg',
    Description: 'If both of his arms are bent at his sides, it is fake. If only one of his arms is bent, it is genuine.' },
  { Name: 'Calm Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/800px-A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Common Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/gleaners.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Dynamic Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Great_Wave_off_Kanagawa2.jpg',
    Description: 'In the fake, Mt. Fuji is very large and takes up most of the space under the wave. If Mt. Fuji is small, it is genuine.' },
  { Name: 'Famous Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_natural_color.jpg',
    Description: 'If her fingers are pointing to the bottom left corner of the picture, it is fake. If her fingers are pointing to the bottom right corner of the picture, it is genuine.' },
  { Name: 'Fine Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/757px-Paul_Gauguin_006.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Flowery Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/464px-Van_Gogh_Vase_with_Fifteen_Sunflowers.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Graceful Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Beauty_looking_back.jpg',
    Description: 'If she is looking to the left, it is fake. If she is looking to the right, it is genuine.' },
  { Name: 'Jolly Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Arcimboldo,_Summer_(1573).jpg',
    Description: 'If the nose is made of a carrot and has green leaves hanging down, it is fake. If the nose is made of a green vegetable, it\'s genuine.' },
  { Name: 'Moody Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/sower.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Moving Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg',
    Description: 'The fake has an upside-down shell.' },
  { Name: 'Neutral Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/758px-Canestra_di_frutta_(Caravaggio).jpg',
    Description: 'If the big green leaf on the top left has a hole in it from being eaten by insects, it is fake. If there is no hole made by insects in the big green leaf, it is genuine.' },
  { Name: 'Nice Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/349px-Manet,_Edouard_-_Young_Flautist,_or_The_Fifer,_1866_(2).jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Perfect Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/cezanne.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Proper Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Edouard_Manet_004.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Quaint Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/300px-Johannes_Vermeer_-_De_melkmeid.jpg',
    Description: 'If she is not wearing a hat, it is fake. If she is wearing a white hat, it is genuine.' },
  { Name: 'Scary Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Toshusai_Sharaku-_Otani_Oniji,_1794.jpg',
    Description: 'If he is only pointing one finger of each hand, it is fake. If he has all fingers sticking out, it is genuine.' },
  { Name: 'Scenic Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/hunters-in-snow.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Serene Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/435px-Dama_z_gronostajem.jpg',
    Description: 'If she is holding a fluffy white cat, it is fake. If she is holding a skinny white ermine, it is genuine.' },
  { Name: 'Solemn Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/las-meninas.jpg',
    Description: 'If the blonde girl is twice as tall as the girl to the left, it is fake. If the blonde girl is close to the same height as the girl to the left, it is genuine.' },
  { Name: 'Warm Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/800px-Goya_Maja_ubrana2.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Wild Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/800px-Fujinraijin-tawaraya.jpg',
    Description: 'If the dark one is on the left and the light one is on the right, it is fake. If the light one is on the left and the dark one is on the right, it is genuine.' },
  { Name: 'Wistful Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Johannes_Vermeer_(1632-1675)_-_The_Girl_With_The_Pearl_Earring_(1665).jpg',
    Description: 'If her hat is red, it is fake. If her hat is blue, it is genuine.' },
  { Name: 'Worthy Painting',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/liberty.jpg',
    Description: 'This painting is always genuine.' },
  { Name: 'Ancient Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Dogu_Miyagi_1000_BCE_400_BCE.jpg',
    Description: 'If its eyes are open, it is fake. If its eyes are closed, it is genuine.' },
  { Name: 'Beautiful Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Venus_de_Milo_Louvre_Ma399.jpg',
    Description: 'If she has long hair down to her shoulders, it is fake. If her hair goes down to cover only her ears, it is genuine.' },
  { Name: 'Gallant Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/David_von_Michelangelo.jpg',
    Description: 'If there is cloth hanging down his right shoulder, it is fake. If his right shoulder is bare, it is genuine.' },
  { Name: 'Great Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Kamehameha_I_full_5111.jpg',
    Description: 'If his fingers are pointing straight out, it is fake. If his fingers are pointing upward, it is genuine.' },
  { Name: 'Motherly Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/She-wolf_suckles_Romulus_and_Remus.jpg',
    Description: 'If there is only one child below the wolf, it is fake. If there are two children, it is genuine.' },
  { Name: 'Mystic Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Nofretete_Neues_Museum.jpg',
    Description: 'If her hat is spherical, it is fake. If her hat is cylindrical, it is genuine.' },
  { Name: 'Robust Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Greek_statue_discus_thrower_2_century_aC.jpg',
    Description: 'If he is holding an object that has bumps on it, it is fake. If he is holding a smooth disc, it is genuine.' },
  { Name: 'Valiant Statue',
    src: 'https://www.thonky.com/animal-crossing-new-leaf/paintings/Nike_of_Samothrake_Louvre_Ma2369_n2.jpg',
    Description: 'If it has bat wings, it is fake. If it has feathery angel wings, it is genuine.' } ],
    "fossils" : [
    { Name: 'Ankylo Skull', Price: '3,500' },
    { Name: 'Ankylo Tail', Price: '2,500' },
    { Name: 'Ankylo Torso', Price: '3,000' },
    { Name: 'Apato Skull', Price: '5,000' },
    { Name: 'Apato Tail', Price: '4,000' },
    { Name: 'Apato Torso', Price: '4,500' },
    { Name: 'Archelon Skull', Price: '4,000' },
    { Name: 'Archelon Torso', Price: '3,500' },
    { Name: 'Dimetrodon Skull', Price: '5,500' },
    { Name: 'Dimetrodon Tail', Price: '4,500' },
    { Name: 'Dimetrodon Torso', Price: '5,000' },
    { Name: 'Diplo Chest', Price: '4,500' },
    { Name: 'Diplo Hip', Price: '4,000' },
    { Name: 'Diplo Neck', Price: '5,000' },
    { Name: 'Diplo Skull', Price: '5,000' },
    { Name: 'Diplo Tail', Price: '4,500' },
    { Name: 'Ichthyo Skull', Price: '2,500' },
    { Name: 'Ichthyo Torso', Price: '2,000' },
    { Name: 'Iguanodon Skull', Price: '4,000' },
    { Name: 'Iguanodon Tail', Price: '3,000' },
    { Name: 'Iguanodon Torso', Price: '3,500' },
    { Name: 'Mammoth Skull', Price: '3,000' },
    { Name: 'Mammoth Torso', Price: '2,500' },
    { Name: 'Megacero Skull', Price: '4,500' },
    { Name: 'Megacero Tail', Price: '3,000' },
    { Name: 'Megacero Torso', Price: '3,500' },
    { Name: 'Pachy Skull', Price: '4,000' },
    { Name: 'Pachy Tail', Price: '3,000' },
    { Name: 'Pachy Torso', Price: '3,500' },
    { Name: 'Parasaur Skull', Price: '3,500' },
    { Name: 'Parasaur Tail', Price: '2,500' },
    { Name: 'Parasaur Torso', Price: '3,000' },
    { Name: 'Plesio Neck', Price: '4,500' },
    { Name: 'Plesio Skull', Price: '4,500' },
    { Name: 'Plesio Torso', Price: '4,500' },
    { Name: 'Ptera Left Wing', Price: '4,500' },
    { Name: 'Ptera Right Wing', Price: '4,500' },
    { Name: 'Ptera Skull', Price: '4,000' },
    { Name: 'Sabertooth Skull', Price: '2,500' },
    { Name: 'Sabertooth Torso', Price: '2,000' },
    { Name: 'Stego Skull', Price: '5,000' },
    { Name: 'Stego Tail', Price: '4,000' },
    { Name: 'Stego Torso', Price: '4,500' },
    { Name: 'Spino Skull', Price: '4,000' },
    { Name: 'Spino Tail', Price: '4,000' },
    { Name: 'Spino Torso', Price: '5,000' },
    { Name: 'Styraco Skull', Price: '3,500' },
    { Name: 'Styraco Tail', Price: '2,500' },
    { Name: 'Styraco Torso', Price: '3,000' },
    { Name: 'Tricera Skull', Price: '5,500' },
    { Name: 'Tricera Tail', Price: '4,500' },
    { Name: 'Tricera Torso', Price: '5,000' },
    { Name: 'T-Rex Skull', Price: '6,000' },
    { Name: 'T-Rex Tail', Price: '5,000' },
    { Name: 'T-Rex Torso', Price: '5,500' },
    { Name: 'Raptor Skull', Price: '3,000' },
    { Name: 'Raptor Torso', Price: '2,500' },
    { Name: 'Name', Price: 'Price' },
    { Name: 'Amber', Price: '1,200' },
    { Name: 'Ammonite', Price: '1,100' },
    { Name: 'Archaeopteryx', Price: '1,300' },
    { Name: 'Coprolite', Price: '1,100' },
    { Name: 'Dinosaur Egg', Price: '1,400' },
    { Name: 'Dinosaur Track', Price: '1,000' },
    { Name: 'Fern Fossil', Price: '1,000' },
    { Name: 'Peking Man', Price: '1,100' },
    { Name: 'Shark Tooth', Price: '1,000' },
    { Name: 'Trilobite', Price: '1,300' } ],
    "fortunes" : [ 
    { Number: '1', Name: 'Mushroom mural' },
    { Number: '2', Name: 'Block floor' },
    { Number: '3', Name: 'Hero\'s clothes' },
    { Number: '4',
      Name: 'consolation prize (random furniture, wallpaper, or carpet)' },
    { Number: '5', Name: 'Hero\'s pants' },
    { Number: '6',
      Name: 'consolation prize (random furniture, wallpaper, or carpet)' },
    { Number: '7', Name: 'Peach\'s parasol' },
    { Number: '8', Name: 'Hero\'s cap' },
    { Number: '9', Name: 'Majora\'s mask' },
    { Number: '10', Name: 'Samus mask' },
    { Number: '11', Name: 'Midna\'s mask' },
    { Number: '12', Name: 'Toad hat' },
    { Number: '13', Name: 'Red Pikmin' },
    { Number: '14', Name: 'Blue Pikmin' },
    { Number: '15', Name: 'Yellow Pikmin' },
    { Number: '16',
      Name: 'consolation prize (random furniture, wallpaper, or carpet)' },
    { Number: '17', Name: 'Block' },
    { Number: '18', Name: 'Coin' },
    { Number: '19', Name: 'Goal Pole' },
    { Number: '20', Name: 'Fire Flower' },
    { Number: '21', Name: 'Super Mushroom' },
    { Number: '22', Name: 'Green Shell' },
    { Number: '23', Name: 'Super Star' },
    { Number: '24', Name: '1-Up mushroom' },
    { Number: '25', Name: '? block' },
    { Number: '26', Name: 'Pipe' },
    { Number: '27', Name: 'Fire Bar' },
    { Number: '28', Name: 'Bill Blaster' },
    { Number: '29', Name: 'Yoshi\'s Egg' },
    { Number: '30',
      Name: 'consolation prize (random furniture, wallpaper, or carpet)' },
    { Number: '31', Name: 'Triple Red Shells' },
    { Number: '32', Name: 'Kart' },
    { Number: '33', Name: 'Pikmin' },
    { Number: '34', Name: 'Blue Falcon' },
    { Number: '35', Name: 'Master Sword' },
    { Number: '36', Name: 'Arwing' },
    { Number: '37', Name: 'Triforce' },
    { Number: '38',
      Name: 'consolation prize (random furniture, wallpaper, or carpet)' },
    { Number: '39', Name: 'S.S. Dolphin' },
    { Number: '40', Name: 'Virtual Boy' },
    { Number: '41', Name: 'Wii Balance Board' },
    { Number: '42', Name: 'Varia Suit pants' },
    { Number: '43', Name: 'Varia Suit shoes' },
    { Number: '44', Name: 'Bad bro\'s stache' },
    { Number: '45', Name: 'Big bro\'s mustache' },
    { Number: '46', Name: 'Varia Suit' },
    { Number: '47', Name: 'Metroid' },
    { Number: '48', Name: 'Triple Bananas' },
    { Number: '49', Name: 'Hero\'s boots' },
    { Number: '50', Name: 'Fi mask' },
    { Number: '51',
      Name: 'Wii U Console (default White, appears as green leaf)' },
    { Number: '52',
      Name: 'Wii U Console (custom Black, appears as red leaf)' },
    { Number: '53', Name: 'Chihuahua ornament' },
    { Number: '54', Name: 'Dalmatian ornament' },
    { Number: '55', Name: 'Dachshund ornament' },
    { Number: '56', Name: 'Labrador ornament' },
    { Number: '57', Name: 'New Nintendo 3DS' } ],
    "donations" : [
        'Bitterling',
        'Pale Chub',
        'Crucian Carp',
        'Dace',
        'Barbel Steed',
        'Carp',
        'Koi',
        'Goldfish',
        'Pop-eyed Goldfish',
        'Killifish',
        'Crawfish',
        'Soft-shelled Turtle',
        'Tadpole',
        'Frog',
        'Freshwater Goby',
        'Loach',
        'Catfish',
        'Eel',
        'Giant Snakehead',
        'Bluegill',
        'Yellow Perch',
        'Black Bass',
        'Pike',
        'Pond Smelt',
        'Sweetfish',
        'Cherry Salmon',
        'Char',
        'Rainbow Trout',
        'Stringfish',
        'Salmon',
        'King Salmon',
        'Shanghai Crab',
        'Guppy',
        'Nibble Fish',
        'Angelfish',
        'Neon Tetra',
        'Piranha',
        'Arowana',
        'Dorado',
        'Gar',
        'Arapaima',
        'Saddled Birchir',
        'Sea Buttefly',
        'Sea Horse',
        'Clown Fish',
        'Surgeonfish',
        'Butterfly Fish',
        'Napoleonfish',
        'Zebra Turkeyfish',
        'Blow Fish',
        'Puffer Fish',
        'Horse Mackerel',
        'Barred Knifejaw',
        'Sea Bass',
        'Red Snapper',
        'Dab',
        'Olive Flounder',
        'Squid',
        'Moray Eel',
        'Ribbon Eel',
        'Football Fish',
        'Tuna',
        'Blue Marlin',
        'Giant Trevally',
        'Ray',
        'Ocean Sunfish',
        'Hammerhead Shark',
        'Shark',
        'Saw Shark',
        'Whale Shark',
        'Oarfish',
        'Coelacanth',
        'Seaweed',
        'Sea Grapes',
        'Sea Urchin',
        'Acorn Barnacle',
        'Oyster',
        'Turban Shell',
        'Abalone',
        'Ear Shell',
        'Clam',
        'Pearl Oyster',
        'Scallop',
        'Sea Anemone',
        'Sea Star',
        'Sea Cucumber',
        'Sea Slug',
        'Flatworm',
        'Mantis Shrimp',
        'Sweetshrimp',
        'Tiger Prawn',
        'Spiny Lobster',
        'Lobster',
        'Snow Crab',
        'Hair Crab',
        'Red King Crab',
        'Giant Spider Crab',
        'Octopus',
        'Spotted Garden Eel',
        'Chambered Nautilus',
        'Horseshoe Crab',
        'Giant Isopod',
        'Species',
        'Common Butterfly',
        'Yellow Butterfly',
        'Tiger Butterfly',
        'Monarch Butterfly',
        'Emperor Butterfly',
        'Agrias Buttefly',
        'Raja Brooke Butterfly',
        'Birdwing Butterfly',
        'Moth',
        'Oak Silk Moth',
        'Honeybee',
        'Bee',
        'Long Locust',
        'Migratory Locust',
        'Locust',
        'Mantis',
        'Orchid Mantis',
        'Brown Cicada',
        'Robust Cicada',
        'Giant Cicada',
        'Walker Cicada',
        'Evening Cicada',
        'Cicada Skin',
        'Lantern Fly',
        'Red Dragonfly',
        'Darner Dragonfly',
        'Banded Dragonfly',
        'Giant Petaltail',
        'Ant',
        'Pondskater',
        'Diving Beetle',
        'Stinkbug',
        'Snail',
        'Cricket',
        'Bell Cricket',
        'Grasshopper',
        'Mole Cricket',
        'Walking Leaf',
        'Walking Stick',
        'Bagworm',
        'Ladybug',
        'Violin Beetle',
        'Longhorn Beetle',
        'Tiger Beetle',
        'Dung Beetle',
        'Wharf Roach',
        'Hermit Crab',
        'Firefly',
        'Fruit Beetle',
        'Scarab Beetle',
        'Jewel Beetle',
        'Miyama Stag',
        'Saw Stag',
        'Giant Stag',
        'Rainbow Stag',
        'Cyclommatus Stag',
        'Golden Stag',
        'Horned Dynastid',
        'Horned Atlas',
        'Horned Elephant',
        'Horned Hercules',
        'Goliath Beetle',
        'Flea',
        'Pillbug',
        'Mosquito',
        'Fly',
        'House Centipede',
        'Centipede',
        'Spider',
        'Tarantula',
        'Scorpion',
        'Amber',
        'Ammonite',
        'Anykylosaurus Skull',
        'Anykylosaurus Torso',
        'Anykylosaurus Tail',
        'Apatosaurus Skull',
        'Apatosaurus Torso',
        'Apatosaurus Tail',
        'Archaeopteryx',
        'Archelon Skull',
        'Archelon Torso',
        'Coprolite',
        'Dimetrodon Skull',
        'Dimetrodon Torso',
        'Dimetrodon Tail',
        'Dinosaur Egg',
        'Dinosaur Track',
        'Diplodocus Skull',
        'Diplodocus Neck',
        'Diplodocus Chest',
        'Diplodocus Hip',
        'Diplodocus Tail',
        'Fern Fossil',
        'Ichthyosaur Skull',
        'Ichthyosaur Torso',
        'Iquanodon Skull',
        'Iquanodon Chest',
        'Iquanodon Tail',
        'Mammoth Skull',
        'Mammoth Torso',
        'Megaceros Skull',
        'Megaceros Torso',
        'Megaceros Tail',
        'Pachysaurus Skull',
        'Pachysaurus Torso',
        'Pachysaurus Tail',
        'Parasaurus Skull',
        'Parasaurus Torso',
        'Parasaurus Tail',
        'Peking Man',
        'Pleiosaur Skull',
        'Pleiosaur Neck',
        'Pleiosaur Torso',
        'Pteranodon Right Wing',
        'Pteranodon Skull',
        'Pteranodon Left Wing',
        'Shark Tooth',
        'Sabretooth Tiger Skull',
        'Sabretooth Tiger Torso',
        'Spinosaurus Skull',
        'Spinosaurus Torso',
        'Spinosaurus Tail',
        'Stegosaurus Skull',
        'Stegosaurus Torso',
        'Stegosaurus Tail',
        'Styracosaurus Skull',
        'Styracosaurus Torso',
        'Styracosaurus Tail',
        'Triceratops Skull',
        'Triceratops Torso',
        'Triceratops Tail',
        'Trilobite',
        'Tyrannosaurus Rex Skull',
        'Tyrannosaurus Rex Torso',
        'Tyrannosaurus Rex Tail',
        'Velociraptor Skull',
        'Velociraptor Torso',
        'In-Game Name',
        'Ancient Statue',
        'Animal Sculpture',
        'Beautiful Sculpture',
        'Gallant Sculpture',
        'Mystic Statue',
        'Robust Sculpture',
        'Valiant Sculpture',
        'Amazing Painting',
        'Basic Painting',
        'Calm Painting',
        'Common Painting',
        'Dynamic Painting',
        'Famous Painting',
        'Fine Painting',
        'Flowery Painting',
        'Good Painting',
        'Jolly Painting',
        'Moody Painting',
        'Moving Painting',
        'Nice Painting',
        'Perfect Painting',
        'Proper Painting',
        'Quaint Painting',
        'Scary Painting',
        'Scenic Painting',
        'Serene Painting',
        'Solemn Painting',
        'Warm Painting',
        'Wild Painting',
        'Wistful Painting',
        'Worthy Painting',
         ]
}

module.exports.data = data